version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=postgresql://postgress_sb3_stlukesapp_user:uw8teD2SEyc2elbSPo8riLhm0AOI3Ewx@dpg-cr5p6gdumphs73e6vq60-a.oregon-postgres.render.com/postgress_sb3_stlukesapp
      - SPRING_DATASOURCE_USERNAME=postgress_sb3_stlukesapp_user
      - SPRING_DATASOURCE_PASSWORD=uw8teD2SEyc2elbSPo8riLhm0AOI3Ewx
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
